### ISSUE TITLE
Where should I find PDF Classifier Jar?

### ISSUE THREAD

**Issue by jgrossi** [SeerLabs/new-csx-extractor#1]
Hi!

First, thanks for the project. It's so much simpler to use :-)

I'm installing the requirements to run the `new-csx-extractor` package inside my Ubuntu server but I cannot find the `PDF Classifier Jar`. Where can I get it?

Thanks!

**Comment by jkillian** [comment]
Hey @jgrossi, glad the project is helping you!

I added the .jar file and the two related files into the `resources/classifier` directory. Let me know if you have any issues, this part is still kind of in-development / experimental :)

Hope this helps!

**Comment by cleegiles** [comment]
Thanks!

How about 2?

Lee

**Comment by jgrossi** [comment]
Hi @JKillian, thanks for including these files. I was not finding `PDF Classifier Jar` on the Internet and you solve that. 

Thanks again!
