### ISSUE TITLE
Did not run because dependency filter AcademicPaperFilter errored

### ISSUE THREAD

**Issue by jgrossi** [SeerLabs/new-csx-extractor#2]
Hi!

I'm already creating the `.txt` file but I'm getting some errors when extracting metadata from papers in PDF format:
- `paperFilename.cite`: _Did not run because dependency filter AcademicPaperFilter errored_
- `paperFilename.header`: _Did not run because dependency extractor HeaderTEIExtractor errored_
- `paperFilename.header.tei`: _Did not run because dependency filter AcademicPaperFilter errored_

Every file above has a XML content but with theses errors inside. 

Any suggestions?

Thanks.

**Comment by jkillian** [comment]
I think the main issue is that you didn't have the `.jar` file that the `AcademicPaperFilter` class needs to run. The extractors that extract citations and headers info depend on this filter, that is, they don't run unless it succeeds (which indicates that the PDF is an academic paper).

You have a couple of options: I think now that you have the `.jar` file, the `AcademicPaperFilter` class should work correctly and the issues should go away. But if they don't, you can do one of two things:
- Go into the extractor class definitions and remove the dependency on the `AcademicPaperFilter` class
- Redefine the dependencies from outside the class definition: `MyExtractorClass.dependencies = ...`

**Comment by jgrossi** [comment]
Hi @JKillian!

First, thank you so much for the support. Really, thank you so much. I'm making some tests with extractions tools in my Masters thesis and CiteSeer is one of them (I'm testing only tools with command line launcher, so, the `new-csx-extractor` repo came to help :-)). I appreciate your help.

I make the changes you've said and I'm extracting now title, authors names, emails, abstract, but no references. I think this can be because ParsCit, but I'm testing it too and the path to `citeExtract.pl` is set but inside the `.cite` file generated I have no references. Moreover I have a error message inside `.academic_filter` generated file: `IOError: [Errno 2] No such file or directory: '/home/vagrant/bin/classifier/acl'`. I have a symlink pointing to `./citeseer/resources/classifier/acl`.

I'll check the references problem (I think it's ParsCit problem) but first of all thank you for the help.

Cheers.

**Comment by jkillian** [comment]
We're always happy when the CiteSeer project helps other people with their research! Glad it's help to you.

As far as the `IOError`, I'm not sure exactly wht's causing the issue for you. I'd just try adjusting the `csxextract/config.py` variable for the file to point to the file directly. Not sure if that will solve it, but worth a try.

As far as ParsCit, are you seeing any error messages or anything from it in the logs or output? Does it work straight form the command line if you just try running it independently?

**Comment by jgrossi** [comment]
I'm running ParsCit itself as a command line program using `bin/citeExtract.pl` file, with the `-m extract_all` flag: `citeExtract.pl -m extract_all paperFilename.txt`. It's working as expected.

I'm already pointing this executable file to the `csxextract/config.py` but without success with CiteSeer. Everything is working except the references extraction. I have no output message neither log messages. I think ParsCit is running including all dependencies but I have only this `paperFilename.cite` file content, generated by CiteSeer:

`<?xml version='1.0' encoding='UTF-8'?>
<algorithms version="110505">
<algorithm name="ParsCit" version="110505">
<citationList>
</citationList>
</algorithm>
</algorithms>`

I'm trying to solve that. Thanks for helping.

**Comment by fanchyna** [comment]
Thank you for using the CiteSeerX new extractor. The new extractor is still under active development. We will try our best to fix bug and make sure all modules are working coherently.

**Comment by jkillian** [comment]
@jgrossi That's the skeleton of the output ParsCit should give you, so at least we know ParsCit is getting run and returning results. Perhaps for the specific PDF you're running it on, it can't find any citations?

**Comment by jgrossi** [comment]
@JKillian I'll try with others PDF files. I appreciate your help :-)

Is there any way to run CiteSeer extraction feature using command line? I know this project `new-csx-extraction` is under development as @fanchyna said, and maybe I can use another way to make my tests using command line. I have to use command line because the output is used inside a PHP program to manage the results and make comparisons. Thanks ;-)

**Comment by jkillian** [comment]
I think this project might be the most useful for you, but @kylemarkwilliams what do you think? Would https://github.com/SeerLabs/CiteSeerExtractor work well for what @jgrossi needs?

**Comment by jgrossi** [comment]
Thanks for the help @JKillian and @fanchyna. The problem about reference extraction was a ParsCit problem, more specifically a CRF++ problem. But now it's working. Thanks for the support. I'm grateful for that.

As I need to use CiteSeer extraction from the command line I think `new-csx-extractor` is the best option, even being in development yet.

If you have any suggestion about which project is better for me I appreciate that, but now for what I need for now this one is working well.

Thanks again for the help. Best regards.

**Comment by jkillian** [comment]
Great! Glad to hear you got it working as needed

**Comment by kylemarkwilliams** [comment]
@JKillian @jgrossi I'm very late to this discussion and it seems you have everything working already. For future reference though, [CiteSeerExtractor](https://github.com/SeerLabs/CiteSeerExtractor) is designed for the use case where you want to hook extraction into another project. Thus, it only allows for requests via the RESTful API, you make the request via HTTP and you get back the result via HTTP. This can be performed from the command line by using a command line client such as cURL.

**Comment by jgrossi** [comment]
Thanks @kylemarkwilliams for the explanation. Actually what I need is to run CiteSeer extraction process tests inside a new app, so it's important to run using the command line. That's why `new-csx-extractor` is better for me. But thanks again for the answer ;-)

**Comment by cleegiles** [comment]
Are you coming back this fall?

Lee
